### ISSUE TITLE
sub-US-03-Backend controlador de producto

### ISSUE THREAD

**Issue by arodrica43** [UB-ES-2018/flipapop#22]
Crear entidad UserProduct:
-Tendrá un User y un Product

Añadir la relacion "products" a la entidad User

Crear controlador ProductController:
-Funcion newProduct() con ruta /product/new (new_product) renderizará el template "newProduct.html.twig" y le pasará a este un formulario de tipo ProductType.

Crear el FormType "ProductType" que solicitará los de un producto

**Comment by jmcano94** [comment]
1. Crear entidad UserProduct:
                -Tendrá un User y un Product
2. Añadir la relacion "products" a la entidad User
3. Crear controlador ProductController:
                -Funcion newProduct() con ruta /product/new (new_product) renderizará el template "newProduct.html.twig" y le pasará a este un formulario de tipo ProductType.

4. Crear el FormType "ProductType" que solicitará los de un producto

**Comment by jmcano94** [comment]
Ya he creado yo la relacion entre usuarios y productos, no era necesaria una nueva entidad
También he dejado creado el FormType de producto

**Comment by jmcano94** [comment]
Story acabada
