### ISSUE TITLE
(4h)US-08 As a seller I want to decide whether the products I've published are visible to anyone on internet, visible to logged users, or just visible to me.

### ISSUE THREAD

**Issue by cmtea** [UB-ES-2018/flipapop#39]
- Backend:
--> Introducir un nuevo Atributo en la entidad Producto, Visibilidad (3 valores). Con int que vayan del 1 al 3.

Los estados estaran definidos como constantes en la Entidad y seran:

const VISIBLE_TODOS = 1;
const VISIBLE_LOGEADO = 2;
const VISIBLE_YO = 3;

Crear metodo puedeVer(User $user) mirar la visibilidad y el estado el usuario (logueado o no o no soy yo)

Añadir al __construct() que la visibilidad sea = 1;
----CHAN

Crear nuevo Controlador AjaxController con una funcion cambiarVisibilidadProducto() con ruta /producto/visbilidad ("ajax_producto_visibilidad"):

/**
*@Route("/producto/visibilidad", name="ajax_producto_visibilidad", options={"expose" = true}

Dentro de este metodo se recibe por post en la Request  (se accede al los datos post mediante $request->request->all()) el id del producto y la nueva visbilidad.
--CARLES

- Frontend:
En vista landingPage.html.twig añadir clausula if que compruebe si el usuario puede ver o no el producto llamando al metodo anterior.

**Comment by arodrica43** [comment]
Para el checkbox al añadir el producto, hace falta añadir un campo a ProductType que se llame visibility (igual que los campos name, price o description). En la comprobación en la landing page se utiliza la sintaxis "if product.puedeVer(user)", por lo que se comenta en el comentario. Aun así, creo recordar que acordamos hacer todo el código en inglés, y ésto rompe un poco (puedeVer). Por otra parte, supongo que la funcion puedeVer(user) devuelve un booleano; es decir, frontend no comprueba si es VISIBLE_TODOS, etc...

**Comment by chan92tkd** [comment]
En la entity Producto he añadido:
1. Una variable llamada "visibility"

2. He añadido 3 constantes con los nombres "VISIBLE_ALL", "VISIBLE_LOGGED" y "VISIBLE_ME", con valores 1, 2 y 3, respectivamente

3. He creado la función puedeVer, llamándola canView(?User $user), que compara que visibilidad tiene el producto con el user si esta logueado o no o si es el mismo, para poder ver el producto

4. En el construct he puesto que el valor inicial sea = 1. (VISIBLE_ALL)

**Comment by cmtea** [comment]
Cierro Issue
