### ISSUE TITLE
(12h)US-09 As a buyer I want to find the products on google search, therefore the site should have a sitemap.xml, so I can find the products easily regardless of my awareness of Flipapop

### ISSUE THREAD

**Issue by cmtea** [UB-ES-2018/flipapop#40]
Documentation: https://www.sitemaps.org/index.html

**Comment by CristinaRL** [comment]
Ahora mismo el sitemap solo contiene la página principal de la web (índice). Para poder incluir las urls de los productos éstos tendrían que poderse mostrar de forma independiente.
Aun así la generación del sitemap XML está preparada para poder añadir fácilmente las urls de los productos una vez hagamos esta modificación.
No sé si sería útil incluir también las páginas como login y signup.

**Comment by cmtea** [comment]
Cierro Issue
