### ISSUE TITLE
Backend:US-11 As a seller I want to declare that a product I manage has been sold, so I will not get more contacts to buy this product

### ISSUE THREAD

**Issue by AinhoaIragorri** [UB-ES-2018/flipapop#55]

**Comment by arodrica43** [comment]
La parte de frontend está hecha.
Es necesario que el la entity product tenga un atributo booleano sold, junto con un getter i un setter. 
Se requiere de una función en AjaxController (que tenga como ruta sell/product/ i como name ajax_sell_product) que permita la ajax request i pase como parámetro de la llamada el atributo sold de Product (con nomnre 'sold'). Por tanto solo es necesario modificar Product i AjaxController.

**Comment by arodrica43** [comment]
Ya he subido los cambios que te comenté. El merge de frontend es automático.

**Comment by jmcano94** [comment]
Resuelto y mergeado
